export const INITIAL_DELAY = 300;

const INCREMENTAL_DELAY = 200;

export const enterTimeout = {
  et1: INITIAL_DELAY + 1 * INCREMENTAL_DELAY,
  et2: INITIAL_DELAY + 2 * INCREMENTAL_DELAY,
  et3: INITIAL_DELAY + 3 * INCREMENTAL_DELAY,
  et4: INITIAL_DELAY + 4 * INCREMENTAL_DELAY,
  et5: INITIAL_DELAY + 5 * INCREMENTAL_DELAY,
  et6: INITIAL_DELAY + 6 * INCREMENTAL_DELAY,
  et7: INITIAL_DELAY + 7 * INCREMENTAL_DELAY,
  et8: INITIAL_DELAY + 9 * INCREMENTAL_DELAY,
  et9: INITIAL_DELAY + 11 * INCREMENTAL_DELAY
};

export const FOOTER_HEIGHT = "42px";

export const NUM_FEATURED_PROJECTS = 3;