export const INITIAL_DELAY = 700;

const INCREMENTAL_DELAY = 300;

const APP_BAR_APPEARS = INITIAL_DELAY;
const APP_BAR_DELAY = 400;
const ABOUT_APPEARS = APP_BAR_APPEARS + APP_BAR_DELAY + INCREMENTAL_DELAY;
const EXPERIENCE_APPEARS = ABOUT_APPEARS + INCREMENTAL_DELAY;
const WORK_APPEARS = EXPERIENCE_APPEARS + INCREMENTAL_DELAY;
const CONTACT_APPEARS = WORK_APPEARS + INCREMENTAL_DELAY;
const RESUME_APPEARS = CONTACT_APPEARS + INCREMENTAL_DELAY;
const HEADLINE_APPEARS = RESUME_APPEARS + INCREMENTAL_DELAY;
const GET_IN_TOUCH_APPEARS = HEADLINE_APPEARS + INCREMENTAL_DELAY;

export const enterTimeout = {
	appBarAppears: APP_BAR_APPEARS,
	aboutAppears: ABOUT_APPEARS,
  	experienceAppears: EXPERIENCE_APPEARS,
  	workAppears: WORK_APPEARS,
  	contactAppears: CONTACT_APPEARS,
  	resumeAppears: RESUME_APPEARS,
  	headlineAppears: HEADLINE_APPEARS,
  	getInTouchAppears: GET_IN_TOUCH_APPEARS,
};



export const FOOTER_HEIGHT = "42px";

export const NUM_FEATURED_PROJECTS = 3;